name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Package source code
        run: |
          tar -czf protoc-gen-go-meta-source-${{ steps.get_version.outputs.VERSION }}.tar.gz --exclude='.git' --exclude='.github' .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: protoc-gen-go-meta-source-${{ steps.get_version.outputs.VERSION }}.tar.gz
          generate_release_notes: true
